version: '3.8'
services:
  food_ordering_db:
    image: postgres:latest
    container_name: food_ordering_db
    environment:
      POSTGRES_USER: ana
      POSTGRES_PASSWORD: ana
      POSTGRES_DB: food_ordering
    volumes:
      - food_ordering-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  restaurant_management_db:
    image: postgres:latest
    container_name: restaurant_management_db
    environment:
      POSTGRES_USER: ana
      POSTGRES_PASSWORD: ana
      POSTGRES_DB: restaurant_management
    volumes:
      - restaurant_management-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  food_ordering-data:
  restaurant_management-data:
