version: '3.8'
services:
  gateway:
    image: gumball7/gateway-elixir:latest
    container_name: gateway-elixir
    ports:
      - "4000:4000"
    depends_on:
      - foodordering
      - restaurantmanagement
      - redis

  foodordering:
    image: gumball7/food-ordering:latest
    container_name: foodordering
    ports:
      - "8000:8000"
    depends_on:
      - food_ordering_db
      - redis

  restaurantmanagement:
    image: gumball7/restaurant-management:latest
    container_name: restaurantmanagement
    ports:
      - "9000:9000"
    depends_on:
      - restaurant_management_db
      - redis


  food_ordering_db:
    image: postgres:latest
    container_name: food_ordering_db
    environment:
      POSTGRES_USER: ana
      POSTGRES_PASSWORD: ana
      POSTGRES_DB: food_ordering
    volumes:
      - food_ordering-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  restaurant_management_db:
    image: postgres:latest
    container_name: restaurant_management_db
    environment:
      POSTGRES_USER: ana
      POSTGRES_PASSWORD: ana
      POSTGRES_DB: restaurant_management
    volumes:
      - restaurant_management-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  food_ordering-data:
  restaurant_management-data:
  redis-data: